config/routes.rb
Hw::Application.routes.draw do
  resources :researches

  resources :customers

  root 'researches#index'

  

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :researches
	
end

app/models/research.rb
class Research < ActiveRecord::Base
	belongs_to :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def new
		@customer = Customer.new
  end

  def show
  	@customer = Customer.find(params[:id])  	
  end

	def index
		@customers = Customer.all
	end

	def create
  	@customer = Customer.new(customer_params)
  	respond_to do |format| 
  		if @customer.save 
  			 OrderMailer.order_email(@customer).deliver
  		   format.html { redirect_to(@customer, notice: 'Order was successfully created.') }
         format.json { render json: @customer, status: :created, location: @customer }
         OrderMailer.order_created(@customer).deliver
      else
         format.html { render action: 'new' }
         format.json { render json: @customer.errors, status: :unprocessable_entity }
      end

  	end
  end 


  private
    def customer_params
    params.require(:customers).permit(:first_name, :last_name, :e_mail)
  end
end

app/controllers/researches_controller.rb
class ResearchesController < ApplicationController
	
	def new
    @research = Research.new
  end

  def show
  	@research = Research.find(params[:id])  	
  end

	def index
		@researches = Research.all
	end

	def create
  	@research = Research.new(research_params)
 
  	@research.save
  	redirect_to @research
  end

  def destroy
    @research = Research.find(params[:id])
    @research.destroy
 
    redirect_to researches_path         
  end

  private
    def research_params
    params.require(:research).permit(:name, :period_of_execution, :cost)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/customers/index.html.erb
<h1>Listing of our customers</h1>
 
<table>
  <tr>
    <th>First Name:</th>
    <th>Second Name:</th>
    <th>E-mail:</th>
  </tr>
 
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.first_name %></td>
      <td><%= customer.last_name %></td>
      <td><%= customer.e_mail %></td>
      </tr>
  <% end %>
    
</table>

app/views/customers/show.html.erb
<h1>Your Order Created!</h1>
<h2>Thank you for choosing us!</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/researches/index.html.erb
<h1>Listing of our researches</h1>
 
<table>
  <tr>
    <th>Name:</th>
    <th>Period of execution:</th>
    <th>Cost:</th>
  </tr>
 
  <% @researches.each do |research| %>
    <tr>
      <td><%= research.name %></td>
      <td><%= research.period_of_execution %></td>
      <td><%= research.cost %></td>
      <td><%= link_to 'Buy this research', research_path(research) %></td>
    </tr>
  <% end %>
</table>

app/views/researches/new.html.erb
<h1>New research</h1>

<%= form_for :research, url: researches_path do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :period_of_execution %><br>
    <%= f.text_field :period_of_execution %>
  </p>

  <p>
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/researches/show.html.erb
<h1>Order form</h1>

<table>
		<tr>
  		<th>Name:</th>
  		<th>Period of execution:</th>
  		<th>Cost:</th>
		</tr>
		<tr>  
			<td><%= @research.name %></td>
			<td><%= @research.period_of_execution %></td>
			<td><%= @research.cost %></td>
		</tr>
</table>

<%= form_for :customers, url: customers_path do |f| %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :e_mail %><br>
    <%= f.text_field :e_mail %>
  </p>

  <p>
    <%= f.submit "Create Order" %>
  </p>
<% end %>

app/views/welcome/home.html.erb
<h1>Hello!</h1>